### ISSUE TITLE
Question : Localized tutorials in the official wiki

### ISSUE THREAD

**Issue by LeRatierBretonnien** [foundry-vtt-community/wiki#39]
Hi, 
We [ie French maintainers of the Foundry French Discord and also modules/systems authors] we would like to propose a "static" page for Foundry tutorials in French. In our humble opinion, it would be great to have it integrated as a new "tab" in the official wiki of Foundry.

What is your opinion on this ? Can we move forward on this or not :) ?

Thanks , LeRatierBretonnien/Sasmira (French Foundry Discord)

**Comment by AnthonyVadala** [comment]
Hello, I responded to you on the official Discord. BUT for others that have the same question, we will be archiving this repo soon as we complete migration to our new community website: [foundryvtt.wiki](https://foundryvtt.wiki). The new wiki platform is powered by Wiki.js which has support for different languages on a per page basis.
